---
title: "LRPD1-Medicina Veterinaria"
author: "Cesar Leyva Molina"
format: html
editor: visual
---

## SISTEMATIZACION Y METODOS ESTADISTICOS
## LRPD1-MEDICINA VETERINARIA Y ZOOTECNIA


# 1. INSTALAR PAQUETES
# install.packages() sirve para descargar paquetes desde internet y agregarlos a R.

install.packages("rio") install.packages("janitor")


# 2. CARGAR PAQUETES
# library() sirve para activar los paquetes y poder usar sus funciones.

library(rio) library(janitor)


# 3. IMPORTAR BASE DE DATOS
# import() permite leer archivos externos: Excel, CSV, TXT, etc. Guardamos la base con el nombre lrpd1

lrpd1 \<- import("data/pacientes_caninos.csv")


# 4. LIMPIAR NOMBRES DE VARIABLES
# clean_names() ordena los nombres: sin espacios, minúsculas, sin símbolos raros. Esto facilita escribir código después.

lrpd1 \<- clean_names(lrpd1)


# 5. MOSTRAR LA BASE DE DATOS
# Solo escribir el nombre del objeto permite ver la tabla completa.

lrpd1


# 6. ESTRUCTURA DE LA BASE
# str() significa structure. Nos muestra: nombre de variables, tipo de dato, primeros valores

str(lrpd1)


# 7. NOMBRES DE COLUMNAS
# names() muestra únicamente los nombres de las variables de la base.

names(lrpd1)

# 8. DIMENSIONES
# dim() indica: filas = número de pacientes columnas = número de variables

dim(lrpd1)


# 9. RESUMEN GENERAL
# summary() resume cada variable.
# Si es numérica:mínimo, máximo, media, mediana.
# Si es cualitativa: frecuencia por categoría.

summary(lrpd1)


# 10. TIPO DE VARIABLE
# class() indica qué tipo de dato tiene.

class(lrpd1$edad_anios)     # numérico
class(lrpd1$sexo) \# texto


# 11. CONVERTIR A FACTOR
# factor() se usa para variables categóricas.
# Ejemplo:
# sexo = M / H
# diagnostico = Otitis / Dermatitis
# ¿Para qué sirve?
# - R reconoce categorías
# - facilita tablas de frecuencia
# - útil para gráficos
# - importante en análisis estadístico futuro

lrpd1$raza <- factor(lrpd1$raza) lrpd1$sexo <- factor(lrpd1$sexo) lrpd1$vacunado <- factor(lrpd1$vacunado) lrpd1$diagnostico <- factor(lrpd1$diagnostico) lrpd1$hospitalizacion <- factor(lrpd1$hospitalizacion)


# 12. VER NIVELES DEL FACTOR
# levels() muestra las categorías internas que tiene la variable.

levels(lrpd1$sexo)
levels(lrpd1$diagnostico)

# 12.1 espero que esten leyendo en verdad todo el LRPD1, este es el punto donde muchos se rinden… tú no eres muchos. Continua los otros codigos


# 13. LONGITUD DE UNA VARIABLE
# length() indica cuántos datos tiene una columna.

length(lrpd1\$sexo)


# 14. MEDIA (PROMEDIO)
# mean() calcula la media aritmética. Sirve para resumir variables numéricas.

mean(lrpd1$edad_anios)
mean(lrpd1$peso_kg)


# 15. DESVIACION ESTANDAR
# sd() mide dispersión.Nos dice cuánto se alejan los datosrespecto al promedio.

sd(lrpd1$edad_anios)
sd(lrpd1$peso_kg)


# 16. TABLAS DE FRECUENCIA
# table() cuenta cuántas veces aparece cada categoría.

table(lrpd1$sexo)
table(lrpd1$diagnostico)


# 17. PROPORCIONES
# prop.table() transforma frecuencias en proporciones.

prop.table(table(lrpd1\$sexo))

# Si buscan porcentaje:

prop.table(table(lrpd1\$sexo)) \* 100


# 18. INTERPRETACION FINAL
# En la parte inferior normalmente veremos:
# - cantidad de machos y hembras
# - diagnóstico más frecuente
# - edad promedio
# - peso promedio
# - variabilidad de edades y pesos
# Esto permite describir la población estudiada.
# Cualquier problema adional que tengan podremos comentarlo el día lunes
